# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MAC', models.CharField(max_length=20)),
                ('points', models.IntegerField()),
                ('MMR', models.IntegerField()),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('hostel', models.CharField(choices=[('Hostel 1', 'Hostel 1'), ('Hostel 2', 'Hostel 2'), ('Hostel 3', 'Hostel 3'), ('Hostel 4', 'Hostel 4'), ('Hostel 5', 'Hostel 5'), ('Hostel 6', 'Hostel 6'), ('Hostel 7', 'Hostel 7'), ('Hostel 8', 'Hostel 8'), ('Hostel 9', 'Hostel 9'), ('Hostel 10', 'Hostel 10'), ('Hostel 11', 'Hostel 11'), ('Hostel 12', 'Hostel 12'), ('Hostel 13', 'Hostel 13'), ('Hostel 14', 'Hostel 14'), ('Hostel 15', 'Hostel 15'), ('Tansa', 'Tansa'), ('QIP', 'QIP')], max_length=10)),
            ],
        ),
    ]
