# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omegle_chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='MAC',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
